version: "3.9"
services:
  internPostgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "intern"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5000:5432"
    volumes:
      - type: volume
        source: internData
        target: /var/lib/postgresql/data
    restart: always
volumes:
  internData:
    name: internData